(source gnu)
;; (source marmalade)
(source melpa)
(source "org" "http://orgmode.org/elpa/")

(depends-on "org-plus-contrib")

(depends-on "isearch")
(depends-on "ace-link")
(depends-on "ace-window")
(depends-on "adaptive-wrap")
(depends-on "align")
(depends-on "anaconda-mode")
(depends-on "ansible-doc")
(depends-on "anzu")
(depends-on "auctex-latexmk")
(depends-on "auctex-skim")
(depends-on "auto-dictionary")
(depends-on "auto-insert")
(depends-on "autorevert")
(depends-on "avy-jump")
(depends-on "beacon")
(depends-on "bibtex")
(depends-on "bind-key")
(depends-on "bookmark")
(depends-on "browse-url")
(depends-on "bug-hunter")
(depends-on "bug-reference")
(depends-on "buttercup")
(depends-on "cabal-mode")
(depends-on "calendar")
(depends-on "cargo")
(depends-on "cask-mode")
(depends-on "company")
(depends-on "company-anaconda")
(depends-on "company-emoji")
(depends-on "company-math")
(depends-on "company-quickhelp")
(depends-on "company-restclient")
(depends-on "company-statistics")
(depends-on "company-tern")
(depends-on "compile")
(depends-on "copyright")
(depends-on "css-mode")
(depends-on "cus-edit")
(depends-on "dash-at-point")
(depends-on "delsel")
(depends-on "desktop")
(depends-on "diff-hl")
(depends-on "diminish")
(depends-on "dired")
(depends-on "dired-x")
(depends-on "doc-view")
(depends-on "easy-kill")
(depends-on "ediff-wind")
(depends-on "el-search")
(depends-on "eldoc")
(depends-on "elide-head")
(depends-on "elisp-mode")
(depends-on "elisp-slime-nav")
(depends-on "embrace")
(depends-on "ensime")
(depends-on "ensime-expand-region")
(depends-on "ert")
(depends-on "etags")
(depends-on "eww")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "face-remap")
(depends-on "fancy-battery")
(depends-on "ffap")
(depends-on "files")
(depends-on "find-func")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-ensime")
(depends-on "flycheck-package")
(depends-on "flycheck-rust")
(depends-on "flycheck-virtualenv")
(depends-on "flyspell")
(depends-on "focus-autosave-mode")
(depends-on "frame")
(depends-on "gh")
(depends-on "gist")
(depends-on "git-commit")
(depends-on "git-timemachine")
(depends-on "gitattributes-mode")
(depends-on "gitconfig-mode")
(depends-on "github-clone")
(depends-on "gitignore-mode")
(depends-on "golden-ratio")
(depends-on "goto-addr")
(depends-on "graphviz-dot-mode")
(depends-on "grep")
(depends-on "hardhat")
(depends-on "haskell")
(depends-on "haskell-compile")
(depends-on "haskell-mode")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-buffers")
(depends-on "helm-command")
(depends-on "helm-company")
(depends-on "helm-descbinds")
(depends-on "helm-elisp")
(depends-on "helm-files")
(depends-on "helm-flycheck")
(depends-on "helm-flyspell")
(depends-on "helm-gitignore")
(depends-on "helm-imenu")
(depends-on "helm-info")
(depends-on "helm-make")
(depends-on "helm-man")
(depends-on "helm-open-github")
(depends-on "helm-projectile")
(depends-on "helm-regexp")
(depends-on "helm-ring")
(depends-on "helm-swoop")
(depends-on "helm-unicode")
(depends-on "hi-lock")
(depends-on "highlight-numbers")
(depends-on "highlight-symbol")
(depends-on "hindent")
(depends-on "hippie-exp")
(depends-on "hl-line")
(depends-on "hl-todo")
(depends-on "homebrew-mode")
(depends-on "html5-schema")
(depends-on "hydra")
(depends-on "ibuffer")
(depends-on "ibuffer-projectile")
(depends-on "ibuffer-vc")
(depends-on "ielm")
(depends-on "ignoramus")
(depends-on "image-file")
(depends-on "info")
(depends-on "ispell")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "json-mode")
(depends-on "json-reformat")
(depends-on "latex")
(depends-on "launch")
(depends-on "locate")
(depends-on "lunaryorn-align")
(depends-on "lunaryorn-buffers")
(depends-on "lunaryorn-elisp")
(depends-on "lunaryorn-files")
(depends-on "lunaryorn-flycheck")
(depends-on "lunaryorn-hippie-exp")
(depends-on "lunaryorn-json")
(depends-on "lunaryorn-markdown")
(depends-on "lunaryorn-osx")
(depends-on "lunaryorn-simple")
(depends-on "lunaryorn-smartparens")
(depends-on "lunaryorn-virtualenv")
(depends-on "lunaryorn-window")
(depends-on "macrostep")
(depends-on "magit")
(depends-on "magit-gh-pulls")
(depends-on "markdown-mode")
(depends-on "mule-cmds")
(depends-on "multiple-cursors")
(depends-on "neotree")
(depends-on "newcomment")
(depends-on "niceify-info")
(depends-on "nlinum")
(depends-on "ns-win")
(depends-on "nxml-mode")
(depends-on "nyan-mode")
(depends-on "osx-trash")
(depends-on "outline")
(depends-on "page")
(depends-on "page-break-lines")
(depends-on "paradox")
(depends-on "pcre2el")
(depends-on "pip-requirements")
(depends-on "play-routes-mode")
(depends-on "popup")
(depends-on "powerline")
(depends-on "proced")
(depends-on "prog-mode")
(depends-on "projectile")
(depends-on "python")
(depends-on "racer")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "recentf")
(depends-on "reftex")
(depends-on "restclient")
(depends-on "reveal-in-osx-finder")
(depends-on "rst")
(depends-on "rust-mode")
(depends-on "savehist")
(depends-on "saveplace")
(depends-on "sbt-mode")
(depends-on "scala-mode")
(depends-on "server")
(depends-on "sh-script")
(depends-on "shell")
(depends-on "simple")
(depends-on "smartparens")
(depends-on "solarized")
(depends-on "spaceline-config")
(depends-on "sql")
(depends-on "sqlup-mode")
(depends-on "stripe-buffer")
(depends-on "subword")
(depends-on "sudo-edit")
(depends-on "sx")
(depends-on "sx-compose")
(depends-on "sx-question-mode")
(depends-on "table")
(depends-on "term")
(depends-on "tern")
(depends-on "tex")
(depends-on "tex-buf")
(depends-on "tex-fold")
(depends-on "tex-mode")
(depends-on "tex-site")
(depends-on "tex-style")
(depends-on "thrift")
(depends-on "tildify")
(depends-on "time")
(depends-on "toml-mode")
(depends-on "typo")
(depends-on "undo-tree")
(depends-on "uniquify")
(depends-on "use-package")
(depends-on "vc-hooks")
(depends-on "visual-fill-column")
(depends-on "visual-regexp")
(depends-on "web-mode")
(depends-on "what-the-commit")
(depends-on "which-func")
(depends-on "which-key")
(depends-on "whitespace")
(depends-on "whitespace-cleanup-mode")
(depends-on "windmove")
(depends-on "winner")
(depends-on "writeroom-mode")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "zone")
(depends-on "zone-nyan")
(depends-on "zop-to-char")
(depends-on "apt-sources-mode")
(depends-on "asm-mode")
(depends-on "batch-mode")
(depends-on "benchmark-init")
(depends-on "calc")
(depends-on "cc-mode")
(depends-on "clojure-mode")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "comint")
(depends-on "compile-bind")
(depends-on "counsel")
(depends-on "crux")
(depends-on "dabbrev")
(depends-on "diff-mode")
(depends-on "elfeed")
(depends-on "erc")
(depends-on "eshell")
(depends-on "flx")
(depends-on "gamegrid")
(depends-on "ggtags")
(depends-on "glsl-mode")
(depends-on "gnuplot-mode")
(depends-on "help-mode")
(depends-on "impatient-mode")
(depends-on "javadoc-lookup")
(depends-on "jekyll")
(depends-on "lisp-mode")
(depends-on "lua-mode")
(depends-on "memoize")
(depends-on "message")
(depends-on "nasm-mode")
(depends-on "notmuch")
(depends-on "octave")
(depends-on "paredit")
(depends-on "paren")
(depends-on "pov-mode")
(depends-on "ps-print")
(depends-on "simple-httpd")
(depends-on "skewer-mode")
(depends-on "skewer-repl")
(depends-on "swiper")
(depends-on "tramp")
(depends-on "uuid-simple")
(depends-on "vimrc-mode")
(depends-on "websocket")
(depends-on "x86-lookup")
(depends-on "flx-ido")
(depends-on "fullframe")
(depends-on "markdown-mode+")
(depends-on "color-moccur")
(depends-on "direx")
(depends-on "direx-grep")
(depends-on "dirtree")
(depends-on "dirtree-prosjekt")
(depends-on "eldoc-eval")
(depends-on "eldoc-extension")
(depends-on "flx-ido")
(depends-on "flx-isearch")
(depends-on "helm-git-grep")
(depends-on "hideshow")
(depends-on "ido")
(depends-on "ido-at-point")
(depends-on "ido-load-library")
(depends-on "ido-select-window")
(depends-on "ido-sort-mtime")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "idomenu")
(depends-on "loccur")
(depends-on "markdown-mode+")
(depends-on "narrowed-page-navigation")
(depends-on "noccur")
(depends-on "occur-context-resize")
(depends-on "osx-lib")
(depends-on "paredit-everywhere")
(depends-on "paredit-menu")
(depends-on "paren-face")
(depends-on "popwin")
(depends-on "powershell")
(depends-on "recompile-on-save")
(depends-on "shut-up")
(depends-on "smex")
(depends-on "ssh")
(depends-on "swoop")
(depends-on "vagrant")
(depends-on "vagrant-tramp")
(depends-on "wand")
(depends-on "noflet")

(depends-on "ac-slime")
(depends-on "ace-isearch")
(depends-on "ace-jump-buffer")
(depends-on "ace-jump-helm-line")
(depends-on "ace-jump-mode")
(depends-on "ace-jump-zap")
(depends-on "ace-link")
(depends-on "ace-window")
(depends-on "adoc-mode")
(depends-on "ag")
(depends-on "aggressive-indent")
(depends-on "alert")
(depends-on "ansi")
(depends-on "ant")
(depends-on "anzu")
(depends-on "aok")
(depends-on "apt-utils")
(depends-on "apt-utils-ido")
(depends-on "async")
(depends-on "atom-dark-theme")
(depends-on "auctex")
(depends-on "auto-complete")
(depends-on "auto-complete-clang")
(depends-on "autobookmarks")
(depends-on "bbdb")
(depends-on "bbyac")
(depends-on "bind-key")
(depends-on "bookmark+")
(depends-on "browse-at-remote")
(depends-on "browse-kill-ring")
(depends-on "browse-kill-ring+")
(depends-on "bts")
(depends-on "bts-github")
(depends-on "c-eldoc")
(depends-on "cask")
(depends-on "cd-compile")
(depends-on "centered-window-mode")
(depends-on "change-inner")
(depends-on "chruby")
(depends-on "cider")
(depends-on "cl-lib-highlight")
(depends-on "clojure-mode")
(depends-on "clojure-mode-extra-font-locking")
(depends-on "cmake-font-lock")
(depends-on "cmake-ide")
(depends-on "cmake-mode")
(depends-on "coffee-mode")
(depends-on "color-identifiers-mode")
(depends-on "color-theme")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "commander")
(depends-on "company")
(depends-on "company-quickhelp")
(depends-on "company-restclient")
(depends-on "concurrent")
(depends-on "cperl-mode")
(depends-on "cpputils-cmake")
(depends-on "css-comb")
(depends-on "css-eldoc")
(depends-on "ctable")
(depends-on "dakrone-theme")
(depends-on "dash")
(depends-on "dash-at-point")
(depends-on "date-at-point")
(depends-on "deferred")
(depends-on "discover")
(depends-on "docean")
(depends-on "dockerfile-mode")
(depends-on "drag-stuff")
(depends-on "easy-kill")
(depends-on "easy-kill-extras")
(depends-on "easy-repeat")
(depends-on "ecukes")
(depends-on "edit-color-stamp")
(depends-on "edit-indirect")
(depends-on "edit-list")
(depends-on "edit-server")
(depends-on "edit-server-htmlize")
(depends-on "ein")
(depends-on "emacs-eclim")
(depends-on "emacsshot")
(depends-on "ember-yasnippets")
(depends-on "epc")
(depends-on "epl")
(depends-on "erc-hl-nicks")
(depends-on "ercn")
(depends-on "ert-async")
(depends-on "eshell-prompt-extras")
(depends-on "espuds")
(depends-on "ess")
(depends-on "ess-R-data-view")
(depends-on "ess-R-object-popup")
(depends-on "ess-smart-equals")
(depends-on "ess-smart-underscore")
(depends-on "eval-in-repl")
(depends-on "evm")
(depends-on "eww-lnum")
(depends-on "expand-region")
(depends-on "eyebrowse")
(depends-on "eyedropper")
(depends-on "f")
(depends-on "feature-mode")
(depends-on "fill-column-indicator")
(depends-on "findr")
(depends-on "fix-word")
(depends-on "flex-isearch")
(depends-on "flycheck")
(depends-on "flycheck-tip")
(depends-on "focus")
(depends-on "font-lock-studio")
(depends-on "foreman-mode")
(depends-on "form-feed")
(depends-on "free-keys")
(depends-on "fuzzy")
(depends-on "geeknote")
(depends-on "ggtags")
(depends-on "gh")
(depends-on "gh-md")
(depends-on "ghc")
(depends-on "ghci-completion")
(depends-on "gist")
(depends-on "git")
(depends-on "git-annex")
(depends-on "git-auto-commit-mode")
(depends-on "git-blame")
(depends-on "git-commit-mode")
(depends-on "git-dwim")
(depends-on "git-gutter")
(depends-on "git-gutter+")
(depends-on "git-link")
(depends-on "git-messenger")
(depends-on "git-rebase-mode")
(depends-on "git-timemachine")
(depends-on "gitattributes-mode")
(depends-on "gitconfig")
(depends-on "gitconfig-mode")
(depends-on "github-browse-file")
(depends-on "github-clone")
(depends-on "gitignore-mode")
(depends-on "gnuplot")
(depends-on "gnuplot-mode")
(depends-on "gnus-x-gm-raw")
(depends-on "go-mode")
(depends-on "golden-ratio")
(depends-on "google")
(depends-on "google-this")
(depends-on "groovy-mode")
(depends-on "haml-mode")
(depends-on "haskell-mode")
(depends-on "haskell-snippets")
(depends-on "helm-R")
(depends-on "helm-ag")
(depends-on "helm-aws")
(depends-on "helm-chrome")
(depends-on "helm-commandlinefu")
(depends-on "helm-flycheck")
(depends-on "helm-flyspell")
(depends-on "helm-github-stars")
(depends-on "helm-gitignore")
(depends-on "helm-google")
(depends-on "helm-gtags")
(depends-on "helm-ls-git")
(depends-on "helm-make")
(depends-on "helm-mt")
(depends-on "helm-open-github")
(depends-on "helm-projectile")
(depends-on "helm-projectile-all")
(depends-on "helm-pydoc")
(depends-on "helm-spotify")
(depends-on "helm-swoop")
(depends-on "helm-wordnet")
(depends-on "hexrgb")
(depends-on "highlight-numbers")
(depends-on "highlight-symbol")
(depends-on "hippie-expand-slime")
(depends-on "history")
(depends-on "howdoi")
(depends-on "ht")
(depends-on "html-script-src")
(depends-on "html-to-markdown")
(depends-on "htmlize")
(depends-on "httprepl")
(depends-on "hy-mode")
(depends-on "ibuffer-git")
(depends-on "ibuffer-projectile")
(depends-on "ibuffer-tramp")
(depends-on "ibuffer-vc")
(depends-on "iedit")
(depends-on "inf-ruby")
(depends-on "inflections")
(depends-on "isearch-symbol-at-point")
(depends-on "jade-mode")
(depends-on "java-snippets")
(depends-on "javap-mode")
(depends-on "jedi")
(depends-on "jedi-direx")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "jtags")
(depends-on "jump")
(depends-on "kill-ring-ido")
(depends-on "kill-ring-search")
(depends-on "kurecolor")
(depends-on "leuven-theme")
(depends-on "list-utils")
(depends-on "log4e")
(depends-on "log4j-mode")
(depends-on "logito")
(depends-on "logstash-conf")
(depends-on "macrostep")
(depends-on "magit-annex")
(depends-on "magit-gh-pulls")
(depends-on "magit-push-remote")
(depends-on "magit-tramp")
(depends-on "make-color")
(depends-on "makey")
(depends-on "malabar-mode")
(depends-on "marcopolo")
(depends-on "maven-test-mode")
(depends-on "minibuf-isearch")
(depends-on "minibuffer-complete-cycle")
(depends-on "moe-theme")
(depends-on "mvn")
(depends-on "names")
(depends-on "noflet")
(depends-on "nvm")
(depends-on "nyan-mode")
(depends-on "nyan-prompt")
(depends-on "omni-kill")
(depends-on "org")
(depends-on "ox-gfm")
(depends-on "ox-reveal")
(depends-on "package-build")
(depends-on "palette")
(depends-on "path-headerline-mode")
(depends-on "pcache")
(depends-on "pcre2el")
(depends-on "pdf-tools")
(depends-on "persistent-soft")
(depends-on "phi-autopair")
(depends-on "phi-grep")
(depends-on "phi-rectangle")
(depends-on "phi-search")
(depends-on "phi-search-dired")
(depends-on "phi-search-mc")
(depends-on "phi-search-migemo")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "pos-tip")
(depends-on "pretty-mode")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "prosjekt")
(depends-on "puppet-mode")
(depends-on "py-smart-operator")
(depends-on "python-environment")
(depends-on "python-info")
(depends-on "r-autoyas")
(depends-on "racket-mode")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-identifiers")
(depends-on "rainbow-mode")
(depends-on "rbenv")
(depends-on "real-auto-save")
(depends-on "realgud")
(depends-on "recompile-on-save")
(depends-on "register-channel")
(depends-on "repeatable-motion")
(depends-on "request")
(depends-on "restclient")
(depends-on "rhtml-mode")
(depends-on "rich-minority")
(depends-on "rinari")
(depends-on "rspec-mode")
(depends-on "ruby-compilation")
(depends-on "ruby-mode")
(depends-on "ruby-test-mode")
(depends-on "ruby-tools")
(depends-on "rust-mode")
(depends-on "rvm")
(depends-on "s")
(depends-on "sass-mode")
(depends-on "save-load-path")
(depends-on "save-sexp")
(depends-on "save-visited-files")
(depends-on "scpaste")
(depends-on "scratch-ext")
(depends-on "scratch-log")
(depends-on "scratch-palette")
(depends-on "scratch-pop")
(depends-on "screenshot")
(depends-on "scss-mode")
(depends-on "shut-up")
(depends-on "simple-call-tree")
(depends-on "simple-call-tree+")
(depends-on "slime")
(depends-on "slime-company")
(depends-on "smart-compile")
(depends-on "smart-forward")
(depends-on "smart-mode-line")
(depends-on "smart-mode-line-powerline-theme")
(depends-on "smart-tab")
(depends-on "smooth-scrolling")
(depends-on "sos")
(depends-on "spaces")
(depends-on "splitjoin")
(depends-on "splitter")
(depends-on "spotify")
(depends-on "ssh")
(depends-on "ssh-config-mode")
(depends-on "stash")
(depends-on "swap-buffers")
(depends-on "swiper")
(depends-on "swiper-helm")
(depends-on "switch-window")
(depends-on "swoop")
(depends-on "sws-mode")
(depends-on "sx")
(depends-on "sync-recentf")
(depends-on "tablist")
(depends-on "tern")
(depends-on "terraform-mode")
(depends-on "toggle-window")
(depends-on "tramp-hdfs")
(depends-on "tramp-term")
(depends-on "transpose-frame")
(depends-on "transpose-mark")
(depends-on "tree-mode")
(depends-on "twittering-mode")
(depends-on "unbound")
(depends-on "undo-tree")
(depends-on "vagrant-tramp")
(depends-on "vimrc-mode")
(depends-on "vkill")
(depends-on "vlf")
(depends-on "watch-buffer")
(depends-on "wc-mode")
(depends-on "web-mode")
(depends-on "websocket")
(depends-on "wide-n")
(depends-on "widget-mvc")
(depends-on "win-switch")
(depends-on "windata")
(depends-on "window-layout")
(depends-on "window-number")
(depends-on "window-numbering")
(depends-on "helm-purpose")
(depends-on "ivy-purpose")
(depends-on "window-purpose")
(depends-on "windresize")
(depends-on "windsize")
(depends-on "winpoint")
(depends-on "with-editor")
(depends-on "yagist")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "yaxception")
(depends-on "zenburn-theme")
(depends-on "zencoding-mode")
(depends-on "zoom-window")
(depends-on "zop-to-char")
(depends-on "ztree")

(depends-on "bm")
(depends-on "cbm")

(depends-on "cabledolphin")                           ; 20160204.138  available    melpa      capture Emacs network traffic

(depends-on "helm-org-rifle")                         ; 20160420.818  available  melpa      Rifle through your Org files

(depends-on "blog-admin")                             ; 20160609.1935 available  melpa      Blog admin for emacs with hexo/org-page supported
(depends-on "code-library")                           ; 20160426.518  available  melpa      use org-mode to collect code snippets
(depends-on "dkdo")                                   ; 20131110.319  available  melpa      Do List major mode based on org-mode.
(depends-on "ego")                                    ; 20160601.2233 available  melpa      a static site generator based on org mode, forked from org-page.
(depends-on "elfeed-org")                             ; 20151003.331  available  melpa      Configure elfeed with one or more org-mode files
(depends-on "epresent")                               ; 20160410.1901 available  melpa      Simple presentation mode for Emacs Org-mode
(depends-on "evil-org")                               ; 20151202.2347 available  melpa      evil keybindings for org-mode
(depends-on "hideshow-org")                           ; 20120223.1450 available  melpa      Provides org-mode like hide and show for hideshow.el
(depends-on "kanban")                                 ; 20150930.917  available  melpa      Parse org-todo headlines to use org-tables as Kanban tables
(depends-on "literate-starter-kit")                   ; 20150730.1154 available  melpa      A literate starter kit to configure Emacs using Org-mode files.
(depends-on "netrunner")                              ; 20160622.642  available  melpa      Create Android: Netrunner decklists using Company, Helm and org-mode
(depends-on "ob-axiom")                               ; 20160310.1353 available  melpa      org-babel for the axiom-environment system
(depends-on "ob-browser")                             ; 20150101.710  available  melpa      Render HTML in org-mode blocks.
(depends-on "ob-coffee")                              ; 20160415.2036 available  melpa      org-babel functions for coffee-script evaluation
(depends-on "ob-cypher")                              ; 20150224.1837 available  melpa      query neo4j using cypher in org-mode blocks
(depends-on "ob-diagrams")                            ; 20160407.537  available  melpa      org-babel functions for diagrams evaluation
(depends-on "ob-elixir")                              ; 20151021.447  available  melpa      org-babel functions for elixir evaluation
(depends-on "ob-go")                                  ; 20160711.1606 available  melpa      org-babel functions for go evaluation
(depends-on "ob-http")                                ; 20160709.224  available  melpa      http request in org-mode babel
(depends-on "ob-ipython")                             ; 20160703.639  available  melpa      org-babel functions for IPython evaluation
(depends-on "ob-kotlin")                              ; 20150312.614  available  melpa      org-babel functions for kotlin evaluation
(depends-on "ob-lfe")                                 ; 20150701.655  available  melpa      org-babel functions for lfe evaluation
(depends-on "ob-lua")                                 ; 20160411.2024 available  melpa      Execute Lua code within org-mode blocks.
(depends-on "ob-ml-marklogic")                        ; 20160508.932  available  melpa      org-babel functions for MarkLogic evaluation
(depends-on "ob-mongo")                               ; 20130718.732  available  melpa      Execute mongodb queries within org-mode blocks.
(depends-on "ob-php")                                 ; 20160505.219  available  melpa      Execute PHP within org-mode blocks.
(depends-on "ob-prolog")                              ; 20150530.937  available  melpa      org-babel functions for prolog evaluation.
(depends-on "ob-redis")                               ; 20160411.2013 available  melpa      Execute Redis queries within org-mode blocks.
(depends-on "ob-restclient")                          ; 20160323.2305 available  melpa      org-babel functions for restclient-mode
(depends-on "ob-sagemath")                            ; 20160517.1728 available  melpa      org-babel functions for SageMath evaluation
(depends-on "ob-sml")                                 ; 20130829.1143 available  melpa      org-babel functions for template evaluation
(depends-on "ob-swift")                               ; 20151204.2311 available  melpa      org-babel functions for swift evaluation
(depends-on "ob-translate")                           ; 20160411.124  available  melpa      Translation of text blocks in org-mode.
(depends-on "ob-typescript")                          ; 20150804.530  available  melpa      org-babel functions for typescript evaluation
(depends-on "org-ac")                                 ; 20140302.413  available  melpa      Some auto-complete sources for org-mode
(depends-on "org-agenda-property")                    ; 20140626.1416 available  melpa      Display org properties in the agenda buffer.
(depends-on "org-alert")                              ; 20160701.1900 available  melpa      Notify org deadlines via notify-send
(depends-on "org-attach-screenshot")                  ; 20160529.737  available  melpa      screenshots integrated with org attachment dirs
(depends-on "org-autolist")                           ; 20150922.705  available  melpa      Improved list management in org-mode
(depends-on "org-beautify-theme")                     ; 20150106.956  available  melpa      A sub-theme to make org-mode more beautiful.
(depends-on "org-bookmark-heading")                   ; 20160325.2359 available  melpa      Emacs bookmark support for org-mode
(depends-on "org-bullets")                            ; 20140918.1137 available  melpa      Show bullets in org-mode as UTF-8 characters
(depends-on "calfw")                                  ; 20160302.1858 available  melpa      Calendar view framework on Emacs
(depends-on "calfw-gcal")                             ; 20120111.200  available  melpa      edit Google calendar for calfw.el.
(depends-on "org-caldav")                             ; 20160614.1342 available  melpa      Sync org files with external calendar through CalDAV
(depends-on "org-capture-pop-frame")                  ; 20160518.308  available  melpa      Run org-capture in a new pop frame
(depends-on "org-chinese-utils")                      ; 20160510.709  available  melpa      Some org-mode utils for Chinese users
(depends-on "org-cliplink")                           ; 20160319.500  available  melpa      insert org-mode links from the clipboard
(depends-on "org-clock-convenience")                  ; 20160529.723  available  melpa      convenience functions for org time tracking
(depends-on "org-context")                            ; 20160108.214  available  melpa      Contextual capture and agenda commands for Org-mode
(depends-on "org-cua-dwim")                           ; 20120202.2134 available  melpa      Org-mode and Cua mode compatibility layer
(depends-on "org-dashboard")                          ; 20150812.302  available  melpa      Visually summarize progress in org files
(depends-on "org-doing")                              ; 20160705.851  available  melpa      Keep track of what you're doing
(depends-on "org-dotemacs")                           ; 20151119.1022 available  melpa      Store your emacs config as an org file, and choose which bits to load.
(depends-on "org-download")                           ; 20160620.607  available  melpa      Image drag-and-drop for Emacs org-mode
(depends-on "org-dp")                                 ; 20160326.603  available  melpa      Declarative Local Programming with Org Elements
(depends-on "org-dropbox")                            ; 20150113.2109 available  melpa      move Dropbox notes from phone into org-mode datetree
(depends-on "org-ehtml")                              ; 20150506.1658 available  melpa      Export Org-mode files as editable web pages
(depends-on "org-elisp-help")                         ; 20130423.1545 available  melpa      org links to emacs-lisp documentation
(depends-on "org-eww")                                ; 20160521.1458 available  melpa      automatically use eww to preview current org-file when save
(depends-on "org-fstree")                             ; 20090723.819  available  melpa      include a filesystem subtree into an org file
(depends-on "org-gcal")                               ; 20160307.1206 available  melpa      Org sync with Google Calendar
(depends-on "org-gnome")                              ; 20150614.757  available  melpa      Orgmode integration with the GNOME desktop
(depends-on "org-grep")                               ; 20151202.429  available  melpa      Kind of M-x rgrep adapted for Org mode.
(depends-on "org-if")                                 ; 20150920.813  available  melpa      Interactive Fiction Authoring System for Org-Mode.
(depends-on "org-iv")                                 ; 20160609.1854 available  melpa      a tool used to view html (in browser) generated by org-file once the org-file changes
(depends-on "org-jekyll")                             ; 20130508.239  available  melpa      Export jekyll-ready posts form org-mode entries
(depends-on "org-jira")                               ; 20150911.558  available  melpa      Syncing between Jira and Org-mode.
(depends-on "org-journal")                            ; 20160624.23   available  melpa      a simple org-mode based journaling mode
(depends-on "org-link-travis")                        ; 20140405.1627 available  melpa      Insert/Export the link of Travis CI on org-mode
(depends-on "org-linkany")                            ; 20160206.2011 available  melpa      Insert link using anything.el/helm.el on org-mode
(depends-on "org-mac-iCal")                           ; 20140107.519  available  melpa      Imports events from iCal.app to the Emacs diary
(depends-on "org-mac-link")                           ; 20160109.1443 available  melpa      Insert org-mode links to items selected in various Mac apps
(depends-on "org-mobile-sync")                        ; 20160629.1307 available  melpa      automatically sync org-mobile on changes
(depends-on "org-multiple-keymap")                    ; 20150328.1806 available  melpa      Set keymap to elements, such as timestamp and priority.
(depends-on "org-octopress")                          ; 20150826.416  available  melpa      Compose octopress articles using org-mode.
(depends-on "org-outlook")                            ; 20160705.638  available  melpa      Outlook org
(depends-on "org-page")                               ; 20160626.108  available  melpa      a static site generator based on org mode
(depends-on "org-pandoc")                             ; 20130729.1850 available  melpa      Export from Org using Pandoc
(depends-on "org-password-manager")                   ; 20160430.1851 available  melpa      Minimal password manager for Emacs Org Mode.
(depends-on "org-pdfview")                            ; 20160125.1254 available  melpa      Support for links to documents in pdfview mode
(depends-on "org-pomodoro")                           ; 20151217.553  available  melpa      Pomodoro implementation for org-mode.
(depends-on "org-present")                            ; 20141109.1756 available  melpa      Minimalist presentation minor-mode for Emacs org-mode.
(depends-on "org-projectile")                         ; 20160617.1206 available  melpa      Repository todo management for org-mode
(depends-on "org-protocol-jekyll")                    ; 20151119.838  available  melpa      Jekyll's handler for org-protocol
(depends-on "org-random-todo")                        ; 20160208.426  available  melpa      notify of random TODO's
(depends-on "org-readme")                             ; 20151204.417  available  melpa      Integrates Readme.org and Commentary/Change-logs.
(depends-on "org-redmine")                            ; 20160711.414  available  melpa      Redmine tools using Emacs OrgMode
(depends-on "org-ref")                                ; 20160713.1305 available  melpa      citations, cross-references and bibliographies in org-mode
(depends-on "org-repo-todo")                          ; 20160307.1029 available  melpa      Simple repository todo management with org-mode
(depends-on "org-rtm")                                ; 20160214.436  available  melpa      Simple import/export from rememberthemilk to org-mode
(depends-on "org-sync")                               ; 20150817.754  available  melpa      Synchronize Org documents with External Issue Trackers
(depends-on "org-table-comment")                      ; 20120209.1051 available  melpa      Org table comment modes.
(depends-on "org-tfl")                                ; 20160407.1440 available  melpa      Transport for London meets Orgmode
(depends-on "org-themis")                             ; 20160121.2004 available  melpa      Experimental project management mode for org-mode
(depends-on "org-time-budgets")                       ; 20151111.1    available  melpa      Define time budgets and display clocked time.
(depends-on "org-toodledo")                           ; 20150301.313  available  melpa      Toodledo integration for Emacs Org mode
(depends-on "org-tracktable")                         ; 20160621.1127 available  melpa      Track your writing progress in an org-table
(depends-on "org-transform-tree-table")               ; 20150110.633  available  melpa      Transform org-mode tree with properties to a table, and the other way around
(depends-on "org-tree-slide")                         ; 20160513.2325 available  melpa      A presentation tool for org-mode
(depends-on "org-trello")                             ; 20160604.645  available  melpa      Minor mode to synchronize org-mode buffer and trello board
(depends-on "org-vcard")                              ; 20151213.2222 available  melpa      org-mode support for vCard export and import.
(depends-on "org-wc")                                 ; 20160204.1715 available  melpa      Count words in org mode trees.
(depends-on "org-webpage")                            ; 20160307.26   available  melpa      a static site generator based on org mode.
(depends-on "org-wunderlist")                         ; 20150817.1913 available  melpa      Org sync with Wunderlist
(depends-on "org2jekyll")                             ; 20160519.1004 available  melpa      Minor mode to publish org-mode post to jekyll without specific yaml
(depends-on "orglue")                                 ; 20150430.513  available  melpa      more functionality to org-mode.
(depends-on "orgtbl-ascii-plot")                      ; 20151215.1351 available  melpa      ascii-art bar plots in org-mode tables
(depends-on "osx-org-clock-menubar")                  ; 20150205.1311 available  melpa      simple menubar integration for org-clock
(depends-on "otama")                                  ; 20160404.332  available  melpa      Org-table Manipulator
(depends-on "outorg")                                 ; 20160327.132  available  melpa      Org-style comment editing
(depends-on "ox-clip")                                ; 20160705.458  available  melpa      Cross-platform Formatted copy commands for org-mode
(depends-on "ox-html5slide")                          ; 20131227.2206 available  melpa      Export org-mode to HTML5 slide.
(depends-on "ox-ioslide")                             ; 20160120.805  available  melpa      Export org-mode to Google I/O HTML5 slide.
(depends-on "ox-nikola")                              ; 20151114.316  available  melpa      Export Nikola articles using org-mode.
(depends-on "ox-rst")                                 ; 20160607.1017 available  melpa      Export reStructuredText using org-mode.
(depends-on "swagger-to-org")                         ; 20160610.1756 available  melpa      Convert a swagger.json file into an org-mode file
(depends-on "syndicate")                              ; 20160603.823  available  melpa      evil keybindings for org-mode
(depends-on "tbx2org")                                ; 20140224.759  available  melpa      Tinderbox to org-mode conversion
(depends-on "timesheet")                              ; 20160530.1445 available  melpa      Timesheet management add-on for org-mode
(depends-on "toc-org")                                ; 20160711.25   available  melpa      add table of contents to org-mode files (formerly, org-toc)
(depends-on "worf")                                   ; 20160704.111  available  melpa      A warrior does not press so many keys! (in org-mode)
(depends-on "yankpad")                                ; 20160707.504  available  melpa      Paste snippets from an org-mode file
