#!/usr/bin/env bash

brew install trash coreutils tern
brew install aspell --with-lang-en
brew tap caskroom/fonts
brew cask install font-xits font-source-code-pro font-source-serif-pro font-consolas-for-powerline font-inconsolata font-monoid
